# Generated by Django 4.2.2 on 2024-09-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='caunt_views',
            new_name='count_views',
        ),
    ]
