# Generated by Django 4.2.2 on 2024-08-30 22:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], max_length=50, verbose_name='Cтатус рассылки')),
                ('server_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ сервера почтового сервиса')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема рассылки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('start_mail', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки')),
                ('stop_mail', models.DateTimeField(default=datetime.datetime(2024, 8, 31, 22, 12, 36, 566662, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки')),
                ('period_mail', models.CharField(choices=[('ежедневно', 'Раз в день'), ('раз в неделю', 'Раз в неделю'), ('раз в месяц', 'Раз в месяц')], default='ежедневно', max_length=100, verbose_name='Периодичность')),
                ('status_mail', models.CharField(choices=[('завершена', 'Завершена'), ('создана', 'Создана'), ('запущена', 'Запущена')], default='создана', max_length=100, verbose_name='Статус')),
                ('next_send_time', models.DateTimeField(blank=True, null=True, verbose_name='Время следующей отправки')),
                ('last_send_at', models.DateTimeField(null=True, verbose_name='Последняя рассылка')),
                ('clients', models.ManyToManyField(related_name='clients', to='emailservice.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')],
            },
        ),
    ]
