# Generated by Django 4.2.2 on 2024-09-03 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='stop_mail',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 4, 45, 27, 123794, tzinfo=datetime.timezone.utc), verbose_name='Конец рассылки'),
        ),
    ]
